#!/bin/bash
# Probe A FULL RUN submitter. Builds a SLURM dependency chain, then returns immediately.
#
#   Stage A  captions        1 job   (CapRL)                     ]
#   Stage B  placebo         1 job   (CPU, needs A)              ] strictly serial: the stimulus
#   Stage C  9 arm jobs      PARALLEL (needs B)                  ] must exist before it is used
#   Stage D  score+analyse   1 job   (needs ALL of C)            ]
#
# Why ONE ARM PER JOB in stage C (not grouped by model as the smoke does):
#   * wall-clock = the slowest ARM, not the slowest model-group;
#   * finest crash isolation -- a failure costs one arm, and it resumes from its own jsonl;
#   * model-load overhead (~2-3 min) is noise against hours of generation, so the grouping
#     optimisation that matters for a 90-minute smoke is irrelevant here;
#   * every arm is then generated by an IDENTICAL procedure -- own process, own load, own
#     batching -- so no arm is treated differently from any other. Symmetry across arms is worth
#     more than a few minutes of load time.
#
# Usage:  bash submit_full.sh [K]      (K defaults to 5; fix it from smoke gate G15 first)
set -euo pipefail
K=${1:-5}
TAG=${TAG:-full}
M=${M:-5}
S=/iopsstor/scratch/cscs/$USER/text_privilege
CODE=$S/code
mkdir -p "$S/logs"

sub() {  # sub <name> <partition> <time> <dependency|-> <command...>
  local name=$1 part=$2 tm=$3 dep=$4; shift 4
  local depflag=""; [ "$dep" != "-" ] && depflag="--dependency=afterok:$dep"
  sbatch --parsable --account=a0174 --partition="$part" --time="$tm" \
         --nodes=1 --ntasks-per-node=1 --job-name="$name" \
         --output="$S/logs/${name}_%j.log" $depflag \
         --wrap "srun --environment=\"\$HOME/toml/vllm011.toml\" bash -lc 'cd $CODE && $*'"
}

# ---- Stage A: captions (the frozen stimulus) --------------------------------------------------
A=$(sub tp_cap normal 04:00:00 - \
      "python tp_pass0_captions.py --captions-per-item $M --tag $TAG")
echo "A captions      = $A"

# Stage A2: question-conditioned captions (arms T3/I3). Independent of A, but chained after it so
# only one CapRL job is resident at a time.
A2=$(sub tp_capq normal 04:00:00 "$A" \
      "python tp_pass0_captions.py --captions-per-item $M --tag $TAG --variant q")
echo "A2 q-captions   = $A2"

# ---- Stage B: placebo assignment (CPU-only, but needs pandas -> container) ---------------------
B=$(sub tp_plc debug 00:20:00 "$A2" \
      "python tp_pass1_placebo.py --tag $TAG")
echo "B placebo       = $B"

# ---- Stage C: seven arms, in parallel ---------------------------------------------------------
# Thinking arms get the long wall-clock: max_tokens 40960 vs 16384, so they dominate.
declare -A TIME=( [T0]=12:00:00 [T1]=12:00:00 [T2]=12:00:00 [T3]=12:00:00
                  [I0]=06:00:00 [I1]=06:00:00 [I2]=06:00:00 [I3]=06:00:00 [A5]=04:00:00 )
CDEPS=""
for ARM in T0 T1 T2 T3 I0 I1 I2 I3 A5; do
  J=$(sub "tp_$ARM" normal "${TIME[$ARM]}" "$B" \
        "python tp_pass2_generate.py --arm $ARM --draws $K --tag $TAG")
  echo "C arm $ARM       = $J"
  CDEPS="${CDEPS:+$CDEPS:}$J"
done

# ---- Stage D: score + analyse under all three metrics + audit ---------------------------------
D=$(sub tp_ana debug 00:40:00 "$CDEPS" \
      "python tp_pass3_score.py --tag $TAG && \
       python tp_pass4_analyze.py --tag $TAG --metric correct && \
       python tp_pass4_analyze.py --tag $TAG --metric correct_tolerant && \
       python tp_pass4_analyze.py --tag $TAG --metric correct_official && \
       python tp_smoke.py --stage audit --tag $TAG")
echo "D analysis      = $D"

echo
echo "Chain submitted. Any arm that hits its wall-clock can simply be resubmitted:"
echo "  python tp_pass2_generate.py --arm <ARM> --draws $K --tag $TAG"
echo "It resumes from its own gen_<ARM>.jsonl and regenerates only what is missing."
